# Generated by Django 4.2.1 on 2023-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='playlists_list',
            field=models.ManyToManyField(to='music.playlist'),
        ),
    ]
