# Generated by Django 4.2.1 on 2023-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Альбомы', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Треки', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterField(
            model_name='group',
            name='date_create',
            field=models.CharField(max_length=255, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название группы'),
        ),
    ]
