# Generated by Django 4.2.1 on 2023-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
